# Generated by Django 5.2.3 on 2025-06-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmarker',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='jobmarker',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='markers/'),
        ),
        migrations.AlterField(
            model_name='jobmarker',
            name='number',
            field=models.IntegerField(),
        ),
    ]
