# Generated by Django 5.2.3 on 2025-06-18 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_jobmarker_description_alter_jobmarker_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmarker',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.job'),
        ),
    ]
